Sprint 7
Yandex-Practicum/MovieQuiz-ios pull request #101
Opened 2022-11-03 19:56 UTC by o-kharitonova

2022-11-03 21:12 UTC, ABashkirova requested changes

2022-11-03 21:12 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITests.swift
> +    }
можно удалить лишний тест, он бесполезен :)

2022-11-03 21:12 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    var questionFactory: QuestionFactoryProtocol?
очень много публичного кода, давайте аккуратно закроем лишний доступ

2022-11-04 07:46 UTC, o-kharitonova commented on MovieQuizUITests/MovieQuizUITests.swift
> +    }
упс, действительно, пропустила:)

2022-11-04 08:18 UTC, ABashkirova commented
Ольга, отлично, работа принята!

Лучше пул реквест отправить в ветку своего репозитория и смерджить после принятия работы. А здесь пул реквест закрыть. 
Небольшая шпаргалка:
[PullRequest.pdf](https://github.com/Yandex-Practicum/MovieQuiz-ios/files/9936277/PullRequest.pdf)

2022-11-07 21:26 UTC, closed without merging