Sprint 05
Yandex-Practicum/MovieQuiz-ios pull request #109
Opened 2022-11-12 11:26 UTC by Andrewsorokin13

Разбил логику работы приложения на несколько частей.
Вынес в отдельную сущность работу по генерации вопросов для квиза.
Написал класс для ведения статистики, которая будет учитывать лучший счёт игры в квиз среди всех игр (даже между перезапусками).
Статистика  сохраняться в UserDefaults.

2022-11-12 12:22 UTC, mmbabaev requested changes

2022-11-12 12:22 UTC, mmbabaev commented on MovieQuiz/Helpers/Constants.swift
> +struct Constatns {
супер

2022-11-12 12:22 UTC, mmbabaev commented on MovieQuiz/Servis/StatisticService/StatisticService.swift
> +        let correct = userDefaults.integer(forKey: Keys.correct.rawValue)
при желании можно вынести в отдельные свойства `correct` и `total`

2022-11-12 12:22 UTC, mmbabaev commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: ShowAlertDelegate?
этот делегат не используется

2022-11-12 12:22 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController/MovieQuizViewController.swift
> +            statisticService?.store(correct: score, total: questionsAmount)
здесь вы увеличиваете количество игр на каждом вопросе. Нужно увеличивать счетчик игр только в конце

2022-11-12 12:22 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-12 16:34 UTC, Andrewsorokin13 commented on MovieQuiz/Presentation/MovieQuizViewController/MovieQuizViewController.swift
> +            statisticService?.store(correct: score, total: questionsAmount)
@mmbabaev  if currentQuestionsIndex == questionsAmount - 1 { ... }, срабатывает перед показом Alert (когда индекс == концу массива вопросов ), в новой версии перенес его и он срабатывает после нажатия на кнопку "Сыграть еще раз"

2022-11-13 17:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController/MovieQuizViewController.swift
> +            statisticService?.store(correct: score, total: questionsAmount)
<img width="569" alt="Screen Shot 2022-11-13 at 20 48 30" src="https://user-images.githubusercontent.com/12600807/201536446-9cfe107d-ceb9-4e03-8854-73b799022f97.png">
Так некорректно. Первый раз данных нет, впоследствии данные показываются без учета последней игры. Например, если поставили рекорд, то он не будет изменен. 

Нужно вызывать перед показом алерта

2024-11-20 21:12 UTC, closed without merging