Sprint 04
Yandex-Practicum/MovieQuiz-ios pull request #114
Opened 2022-11-15 18:26 UTC by DmitryRedka

Done homework for 4 sprint

2022-11-15 20:32 UTC, ABashkirova requested changes
Привет!
Логика приложения реализована верно. Вот что нужно поправить по верстке:

1. Лаунч скрин - contentMode изображения стоит неверный, изображение не будет заполнять полностью пространство без искажений. Нужно выставить верный
2. Фон главного экрана должен быть YP Black
3. Постер имеет не тот радиус скругления, а при старте приложения вовсе не имеет скруглений
4. Постер, аналогично ланч скрину, имеет не верный contentMode
5. Констренты на кнопках стоит удалить, но добавить на стек с кнопками констрейнт высоты
6. По макетам кнопки должны быть прижаты к нижней safearea (0 констрейнт), но этого констрейнта нет. Надо добавить на главный стек-контейнер. При этом такой констрейнт скорее всего будет конфликтовать с лейблом вопроса: лейбл перестанет вмещать полностью вопрос. Чтобы этого избежать, нужно добавить пространства вопросу, то есть уменьшить отступы. Проверяй на разных девайсах.
<img width="505" alt="Снимок экрана 2022-11-16 в 00 26 27" src="https://user-images.githubusercontent.com/20269264/202018673-bac844b5-787a-4522-8f16-9513c912eb34.png">

2022-11-15 20:32 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func show(quiz questinIndex: Int) {
я всегда включаю [проверку правописания](https://sarunw.com/posts/spell-checking-in-xcode/), чтобы не допускать опечаток, рекомендую включить и проверить проект

2022-11-15 20:32 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Всегда используй наиболее короткую форму синтаксиса
```suggestion
        present(alert, animated: true, completion: nil)
```

2022-11-15 20:32 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 6 // толщина рамки
Это радиус скругления, и он не по макету

2022-11-15 20:32 UTC, ABashkirova commented on MovieQuiz/Resources/Info.plist
> +             <string>YS Display-Thin</string>
Лишнее можно удалить

2022-11-15 20:33 UTC, ABashkirova commented
Обращу внимание, что пользователь может случайно прожать два раза кнопку ответа или даже много и быстро понажимать на кнопки. 
Это может привести к неверному увеличению счетчика, или лишнего вызова алерта с результатом. 
Принято такое поведение блокировать на время выполнения операции запроса следующего вопроса.
Можно использовать свойство [isEnabled](https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled). До начала смены вопроса "выключать" кнопку, после отображения свежих данных "включать"

2022-11-17 16:30 UTC, ABashkirova requested changes
contentMode у постера стоит такой, что неформатная картинка будет искажаться. Нужен aspect fill. Тоже самое касается и картинки на launch screen 
<img width="505" alt="Снимок экрана 2022-11-17 в 20 28 14" src="https://user-images.githubusercontent.com/20269264/202502342-edb51d92-c5ab-4597-ad9a-500e4b332aac.png">

Остальные замечания исправлены 👍🏻

2022-11-17 16:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var noButton: UIButton!
private - об этом надо помнить :)

2022-11-17 16:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
```suggestion
```

2022-11-17 16:30 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
```suggestion
```

2022-11-17 16:30 UTC, ABashkirova commented on MovieQuiz/Resources/Info.plist
> -             <string>YS Display-Thin</string>
а почему прям все удалил? Нужно было оставить только необходимые.

2022-11-17 16:35 UTC, ABashkirova commented
@DmitryRedka попрошу этот пулреквест закрыть и создать новый в своем репозитории. 
[PullRequest.pdf](https://github.com/Yandex-Practicum/MovieQuiz-ios/files/10033584/PullRequest.pdf)

2022-11-17 16:39 UTC, DmitryRedka commented on MovieQuiz/Resources/Info.plist
> -             <string>YS Display-Thin</string>
Не знаю какие нужны, поэтому удалил все))

2022-11-17 16:45 UTC, closed without merging

2022-11-17 16:46 UTC, DmitryRedka commented
create new PR