Второй ревью
Yandex-Practicum/MovieQuiz-ios pull request #123
Opened 2022-11-20 14:45 UTC by pupersa23

2022-11-20 17:05 UTC, ABashkirova commented
У изображений постера и ланч-скрина надо сменить contentMode: сейчас изображение может выглядеть некорректно, имея боковые полосы, чтобы такого не было надо задать такое значение, чтобы изображение заполняло всё пространство, но не искажалось при растягивании
<img width="300" alt="Снимок экрана 2022-11-20 в 18 58 28" src="https://user-images.githubusercontent.com/20269264/202915253-66ab22d3-ce36-45a0-a3ef-a3e935a78407.png"><img width="300" alt="Снимок экрана 2022-11-20 в 18 58 38" src="https://user-images.githubusercontent.com/20269264/202915250-c69aca32-9899-40af-9440-2abde082252d.png">

Еще у кнопок выставлен разный tint color, за счет чего они по разному выглядят при блокировке и нажатии. Лучше чтобы было одинаково
<img width="1112" alt="Снимок экрана 2022-11-20 в 19 00 08" src="https://user-images.githubusercontent.com/20269264/202915413-ef238533-4a8b-4b37-b7d4-dd7b27394a52.png">
<img width="1147" alt="Снимок экрана 2022-11-20 в 19 00 12" src="https://user-images.githubusercontent.com/20269264/202915407-f3ae2345-b747-41a2-b9a3-5eb2421681e6.png">

2022-11-20 17:06 UTC, ABashkirova requested changes

2022-11-20 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }else{
После ключевых слов пробелы:
```suggestion
        } else {
```

2022-11-20 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
cornerRadius и masksToBounds достаточно настроить один раз, можно во viewDidLoad

2022-11-22 07:17 UTC, pupersa23 commented
Внес правки, вроде теперь все работает как надо)

2022-11-23 08:46 UTC, ABashkirova approved these changes
👍🏻

2022-12-04 10:18 UTC, closed without merging