Sprint 04
Yandex-Practicum/MovieQuiz-ios pull request #137
Opened 2022-11-23 14:05 UTC by kraevop

Sprint task number 4 has been completed

2022-11-24 15:11 UTC, mmbabaev requested changes

2022-11-24 15:11 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    // MARK: Actions
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs  другие типы - сверху или снизу

2022-11-24 15:11 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 6
значение не по дизайну

2022-11-24 15:11 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { self.showNextQuestionOrResults()
лучше перенести на следующую строку вызов функции

2022-11-24 15:11 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { self.showNextQuestionOrResults()
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-24 15:11 UTC, mmbabaev commented
Также шрифты не меняются в приложении. В учебнике допущена ошибка, поэтому этот пункт необязателен. 
На скрине показал как нужно сделать: 
1) Шрифты добавлены в Group (серая папка)
2) Шрифтам проставлена галочка Target Membership  (справа)

<img width="1356" alt="Screen Shot 2022-11-17 at 20 15 01" src="https://user-images.githubusercontent.com/12600807/202513128-d74c5681-7a76-4778-ae5b-0fbcd44f0893.png">

Полезная статья, которая помогла мне разобраться в свое время: 
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

2022-11-24 22:02 UTC, kraevop commented
Corrected comments on the project

2022-11-26 08:50 UTC, mmbabaev commented
Заметил также, что шрифт одного лейбла выставлен как default label color. Этот цвет динамический, меняется в зависимости от выбранной темы. Поэтому в темной теме он черный. 

Т.к. сейчас приложение не поддерживает смену темы, то лучше поставить просто белый.

2022-11-26 08:50 UTC, mmbabaev commented
<img width="766" alt="Screen Shot 2022-11-26 at 11 49 02" src="https://user-images.githubusercontent.com/12600807/204080594-55f2eef8-c0dd-430e-b9b0-bf0461c6fcb8.png">

2022-11-30 14:42 UTC, closed without merging