Sprint 05
Yandex-Practicum/MovieQuiz-ios pull request #139
Opened 2022-11-24 08:12 UTC by totoriole

2022-11-25 09:19 UTC, ABashkirova requested changes
Дополнительно, давай поправим:
1) цвет фона на Black YP
2) закругление при старте у постера
<img width="505" alt="Снимок экрана 2022-11-25 в 11 14 14" src="https://user-images.githubusercontent.com/20269264/203944383-d2ea76f8-15e1-4dab-bd7d-9cd74ff5f5c4.png">

3) верстку верхн-низ у главного стека: по макетам сверху **10** от safearea, а не 0, а снизу **0 от safearea**, а не 34 от superview. Дополнительно не забудь проверить что текст вопроса влезает и отображается полностью - иначе, увеличь пространство ему (компромисс, это ОК)

<img width="262" alt="Снимок экрана 2022-11-25 в 11 16 59" src="https://user-images.githubusercontent.com/20269264/203944631-8887886f-0e29-48ad-80f1-ffd4db15765e.png">

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
Привет!  Давай этот пулреквест закроем. И сделаем новый в твоем репозитории. 
Вот шпаргалка:
[PullRequest.pdf](https://github.com/Yandex-Practicum/MovieQuiz-ios/files/10090187/PullRequest.pdf)

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Models/GameRecord.swift
> +        }
Можно возвращать сразу результат вычисления выражения:
```suggestion
        return lhs.correct < rhs.correct
```

А еще, если функция однострочная, можно опускать return:
```suggestion
        lhs.correct < rhs.correct
```

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +"""
Код гораздо проще читать, когда вложенность "столбцов" одинаковая.
```suggestion
            Ваш результат: \(correctAnswers) из 10,
            Количество сыгранных квизов: \(statisticService.gamesCount)
            Рекорд: \(statisticService.bestGame.correct)/\(statisticService.bestGame.total) (\(statisticService.bestGame.date.dateTimeString))
            Средняя точность: \(String(format: "%.2f", statisticService.totalAccuracy))%
            """
```

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            return (getCorrect/getTotal) * 100
Вокруг операторов принято расставлять пробелы
```suggestion
            return (getCorrect / getTotal) * 100
```

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
1) Лишние скобки:
2) можно же тоже вынести в свойства класса, и например заприватить. А обращаться уже как correct и total
```suggestion
            let getCorrect = Double(userDefaults.integer(forKey: Keys.correct.rawValue))
            let getTotal = Double(userDefaults.integer(forKey: Keys.total.rawValue))
```

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            return data
```suggestion
            return userDefaults.integer(forKey: Keys.gamesCount.rawValue)
```

2022-11-25 09:19 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    }
Сначала перечисляют все свойства, затем все функции. Инит тоже функция, поэтому давай поправим

2022-11-25 11:11 UTC, totoriole commented on MovieQuiz/Models/GameRecord.swift
> +        }
Круто, знала это, но почему-то даже не вспомнила, пока что все усложняю и топорно делаю =(( 
А как сразу красивее и лаконичнее код смотрится))

2022-11-25 11:25 UTC, totoriole commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
Александра, можете помочь, при вынесении в свойства класса выдает ошибку инициализации, что-то не пойму, необходимо их инициализировать?
"Cannot use instance member 'userDefaults' within property initializer; property initializers run before 'self' is available"

2022-11-25 11:34 UTC, totoriole commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
<img width="1109" alt="Снимок экрана 2022-11-25 в 14 31 57" src="https://user-images.githubusercontent.com/89274127/203976923-e6310117-ae69-4d86-9471-d841b6229c69.png">

2022-11-25 11:36 UTC, ABashkirova commented on MovieQuiz/Models/GameRecord.swift
> +        }
Лучше иногда топорно, зато верно :) Не переживай, это с опытом и насмотренностью придет

2022-11-25 11:38 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
Нужно добавить свойства с гетерами сеттерами, по аналогии gamesCount, gameRecord)

```
private(set) var correct: Double {
 get { } 
 set { } 
}
```

2022-11-25 11:38 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
И использовать сразу userDefaults.double (или float я не помню)

2022-11-25 11:39 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
private(set) – это модификатор, который запрещает изменять свойство вне класса, только читать. Можно просто private

2022-11-25 11:55 UTC, totoriole commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +            let getTotal = Double((userDefaults.integer(forKey: Keys.total.rawValue)))
Спасибо за подсказку, если свойства вычисляемые, то им не нужен инициализатор))

2022-11-26 08:53 UTC, ABashkirova approved these changes

2022-11-26 08:53 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticServiceImplementation.swift
> +        userDefaults.set(userDefaults.integer(forKey: "correct") + count, forKey: "correct")
Тогда уж: 
`userDefaults.set(correct + count, forKey: "correct")`

а если бы сеттер написала в correct, то можно было бы просто `correct += count` :)

2022-11-26 09:37 UTC, closed without merging